---
title           : "My preregistration for Productivity Course"
shorttitle      : "My preregistration"
date            : "2024/10/2)`"

author: 
  - name        : Andrew Vermey
    affiliation : Author
  - name        : Dirk Steinke
    affiliation : Advisor

affiliation:
  - id          : 1084318
    institution : University of Guelph
  - id          : N/A
    institution : University of Guelph

output: prereg::prereg_pdf
---

<!-- To keep pre-registrations to a reasonable length for readers, we recommend answers fit within a single page .pdf document, roughly 3200 characters. Read more about this here: https://aspredicted.org/messages/why_limits.php -->


## Data collection
<!-- Have any data been collected for this study already? (Note: "Yes" is not an accepted answer.) -->


**It's complicated.** We have already collected some samples but not enough to fill a plate, thus PCR has not occured yet.



## Hypothesis
<!-- What's the main question being asked or hypothesis being tested in this study? -->

> DNA movement throughout environmental compartments can help us track animal migration patterns without needing to harass or capture wildlife.


## Dependent variable
<!-- Describe the key dependent variable(s) specifying how they will be measured. -->

> The DNA strands collected


## Conditions
<!-- How many and which conditions will participants be assigned to? -->

> Samples will be collected by ECCC on their expediditon




## Analyses
<!-- Specify exactly which analyses you will conduct to examine the main question/hypothesis. -->

> Example: Linear regression looking at the significace 


## Outliers and exclusions
<!-- Describe exactly how outliers will be defined and handled, and your precise rule(s) for excluding observations. -->

> If reads are too damaged they will be excluded


## Sample size
<!-- How many observations will be collected or what will determine sample size? No need to justify decision, but be precise about _exactly_ how the number will be determined. -->

> Example: Depending on how many samlpes we recive


## Other
<!-- Anything else you would like to pre-register? (e.g., secondary analyses, variables collected for exploratory purposes, unusual analyses planned?) -->


## Study type
Finally. For record keeping purposes, please tell us the type of study you are pre-registering.

* Class project or assignment
* Experiment
* Survey
* Observational/archival study
* Other:


# References
## 
\vspace{-2pc}
\setlength{\parindent}{-0.5in}
\setlength{\leftskip}{-1in}
\setlength{\parskip}{8pt}
\noindent
